trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build_and_test_stage
  jobs:
  - job: Build_and_test_job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: "Use .NET Core SDK 3.1.x"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: CmdLine@2
      displayName: "Suppress welcome message"
      inputs:
        script: 'touch "$HOME"/.dotnet/"$(dotnet --version)".dotnetFirstUseSentinel'
    - task: DotNetCoreCLI@2
      displayName: "Build Huxley 2"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: "Unit test Huxley 2"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(ab7bef83-a68d-438a-8d49-b2e42b8bc6a8)'
        appType: 'webAppLinux'
        WebAppName: 'lakeview'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/Huxley2.zip'
        RuntimeStack: 'DOTNETCORE|3.1'
        ArtifactName: 'drop'
        publishLocation: 'Container'
